name: PHP CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

     # ติดตั้ง phpcs แบบ global (ไม่ใช้ composer.json)
    - name: Install PHPCS
      run: |
        curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
        chmod +x phpcs.phar

    - name: Run Lint (CodeSniffer)
      run: php phpcs.phar src/

